language: generic

sudo: required

services:
  - docker

stages:
    - name: base images
      if: branch = latest

    - name: extra images

jobs:
  include:
    - stage: base images
    - script: docker build -f python3/Dockerfile .
    - script: docker build -f python2/Dockerfile .

    - stage: extra images
    - script: docker build -f python2/Dockerfile.dev .
    - script: docker build -f python2/Dockerfile.jupyter .
    - script: docker build -f python2/Dockerfile.talib .

    - script: docker build -f python3/Dockerfile.dev .
    - script: docker build -f python3/Dockerfile.jupyter .
    - script: docker build -f python3/Dockerfile.talib .
