language: generic

sudo: required

services:
  - docker

jobs:
  include:
    - stage: build base images
      if: branch = latest
    - script: docker build -f python3/Dockerfile .
    - script: docker build -f python2/Dockerfile .

    - stage: build extra images
    - script: docker build -f python2/Dockerfile.dev .
    - script: docker build -f python2/Dockerfile.jupyter .
    - script: docker build -f python2/Dockerfile.talib .

    - script: docker build -f python3/Dockerfile.dev .
    - script: docker build -f python3/Dockerfile.jupyter .
    - script: docker build -f python3/Dockerfile.talib .
