FROM    alpine:latest

ENV     ZIPLINE_REF master

ENV     TALIB_REF 0.4.0

RUN     apk add --no-cache --virtual .build-deps \
            build-base \
            ca-certificates \
            freetype-dev \
            gfortran \
            git  \
            libpng-dev \
            linux-headers \
            openblas-dev \
            py-pip \
            python2-dev && \
        apk add --no-cache --virtual .hdf5-dev \
            --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing/ \
            hdf5-dev

RUN     ln -s /usr/include/locale.h /usr/include/xlocale.h

WORKDIR /src

ADD     https://downloads.sourceforge.net/project/ta-lib/ta-lib/$TALIB_REF/ta-lib-$TALIB_REF-src.tar.gz \
            ta-lib-src.tar.gz

RUN     tar -vxzf ta-lib-src.tar.gz && \
        cd ta-lib && \
        ./configure --prefix=/usr && \
        make install && \
        cd .. && \
        rm -vr ta-lib ta-lib-src.tar.gz

ADD     https://github.com/quantopian/zipline/archive/$ZIPLINE_REF.tar.gz \
            zipline.tar.gz

RUN     tar -vxzf zipline.tar.gz && \
        mv -v zipline-$ZIPLINE_REF zipline && \
        rm -v zipline.tar.gz

WORKDIR /src/zipline

RUN     pip install --no-cache-dir \
            -r etc/requirements.txt \
            -r etc/requirements_blaze.txt \
            -r etc/requirements_dev.txt  \
            -r etc/requirements_talib.txt

RUN     pip install --no-cache-dir -e .

RUN     apk del --no-cache .build-deps .hdf5-dev && \
        apk add --no-cache \
            openblas \
            libstdc++ \
            py-pip python2 && \
        apk add --no-cache \
            --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing/ \
            hdf5

ENV     ZIPLINE_ROOT /zipline

RUN     addgroup zipline && \
            adduser -D -h $ZIPLINE_ROOT -s /sbin/nologin -G zipline zipline

USER    zipline

VOLUME  $ZIPLINE_ROOT

CMD     zipline
